# This workflow will do a clean installation of node dependencies, cache/restore them,
#   build the source code and run tests across different versions of node
#   For more information see:
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [20, 22, 23]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: corepack enable
        run: corepack enable
      - name: Update yarn
        run: |
          yarnVersion=$(jq -r ".packageManager" package.json | sed "s/^[^:]*@//")
          yarn set version "${yarnVersion}"
      - name: Yarn version
        run: yarn --version
      - name: Generate simple .yarnrc.yml
        run: |
          echo "nodeLinker: node-modules" >> .yarnrc.yml
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test
